# Generated by Django 6.0.7 on 2026-07-10 23:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('partners', '0001_initial'),
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceivingInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=50, unique=True, verbose_name='رقم الفاتورة')),
                ('status', models.CharField(choices=[('DRAFT', 'مسودة'), ('PENDING', 'بانتظار الاعتماد'), ('APPROVED', 'معتمد'), ('CANCELLED', 'ملغي')], default='DRAFT', max_length=10, verbose_name='الحالة')),
                ('date', models.DateField(verbose_name='التاريخ')),
                ('time', models.TimeField(auto_now_add=True, verbose_name='الوقت')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='الإجمالي')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الاعتماد')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='محذوف')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_receiving', to=settings.AUTH_USER_MODEL, verbose_name='اعتمده')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receiving_invoices', to=settings.AUTH_USER_MODEL, verbose_name='أنشأه')),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partners.farmer', verbose_name='الرعوي')),
                ('warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.warehouse', verbose_name='المخزن')),
            ],
            options={
                'verbose_name': 'فاتورة استلام',
                'verbose_name_plural': 'فواتير الاستلام',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReceivingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='الكمية')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='سعر الوحدة')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='الإجمالي')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='receiving.receivinginvoice', verbose_name='الفاتورة')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='الصنف')),
                ('quality_grade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.qualitygrade', verbose_name='درجة الجودة')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.unit', verbose_name='الوحدة')),
            ],
            options={
                'verbose_name': 'صنف استلام',
                'verbose_name_plural': 'أصناف الاستلام',
            },
        ),
        migrations.CreateModel(
            name='ReturnInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=50, unique=True, verbose_name='رقم الفاتورة')),
                ('status', models.CharField(choices=[('DRAFT', 'مسودة'), ('APPROVED', 'معتمد'), ('CANCELLED', 'ملغي')], default='DRAFT', max_length=10, verbose_name='الحالة')),
                ('date', models.DateField(verbose_name='التاريخ')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='الإجمالي')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='محذوف')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='أنشأه')),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partners.farmer', verbose_name='الرعوي')),
                ('receiving_invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='receiving.receivinginvoice', verbose_name='فاتورة الاستلام الأصلية')),
            ],
            options={
                'verbose_name': 'مرتجع استلام',
                'verbose_name_plural': 'مرتجعات الاستلام',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReturnItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='الكمية')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='سعر الوحدة')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='الإجمالي')),
                ('reason', models.TextField(blank=True, verbose_name='السبب')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='الصنف')),
                ('return_invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='receiving.returninvoice', verbose_name='الفاتورة')),
            ],
            options={
                'verbose_name': 'صنف مرتجع',
                'verbose_name_plural': 'أصناف المرتجع',
            },
        ),
    ]
