# Generated by Django 6.0.7 on 2026-07-10 23:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('partners', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_number', models.CharField(max_length=50, unique=True, verbose_name='رقم السند')),
                ('payment_method', models.CharField(choices=[('CASH', 'نقدي'), ('BANK_TRANSFER', 'تحويل بنكي'), ('CHECK', 'شيك'), ('OTHER', 'أخرى')], default='CASH', max_length=20, verbose_name='طريقة الدفع')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='المبلغ')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('date', models.DateField(verbose_name='التاريخ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='محذوف')),
                ('bank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.bank', verbose_name='الحساب البنكي')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partners.buyer', verbose_name='الرعوي')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='أنشأه')),
            ],
            options={
                'verbose_name': 'سند قبض',
                'verbose_name_plural': 'سندات القبض',
                'ordering': ['-created_at'],
            },
        ),
    ]
