# Generated by Django 6.0.7 on 2026-07-10 23:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('partners', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FarmerSettlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('settlement_number', models.CharField(max_length=50, unique=True, verbose_name='رقم التسوية')),
                ('period_start', models.DateField(verbose_name='بداية الفترة')),
                ('period_end', models.DateField(verbose_name='نهاية الفترة')),
                ('total_sales', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='إجمالي المبيعات')),
                ('total_commissions', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='إجمالي العمولات')),
                ('total_discounts', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='إجمالي الخصومات')),
                ('total_expenses', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='إجمالي المصروفات')),
                ('total_paid', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='إجمالي المدفوعات')),
                ('net_payable', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='صافي المستحق')),
                ('status', models.CharField(choices=[('DRAFT', 'مسودة'), ('PENDING', 'بانتظار الاعتماد'), ('APPROVED', 'معتمد')], default='DRAFT', max_length=10, verbose_name='الحالة')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الاعتماد')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='محذوف')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settlements_approved', to=settings.AUTH_USER_MODEL, verbose_name='اعتمده')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settlements_created', to=settings.AUTH_USER_MODEL, verbose_name='أنشأه')),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partners.farmer', verbose_name='الرعوي')),
            ],
            options={
                'verbose_name': 'تسوية رعوي',
                'verbose_name_plural': 'تسويات الرعية',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentVoucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voucher_number', models.CharField(max_length=50, unique=True, verbose_name='رقم السند')),
                ('payment_method', models.CharField(choices=[('CASH', 'نقدي'), ('BANK_TRANSFER', 'تحويل بنكي'), ('CHECK', 'شيك'), ('OTHER', 'أخرى')], default='CASH', max_length=20, verbose_name='طريقة الدفع')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='المبلغ')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('date', models.DateField(verbose_name='التاريخ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='محذوف')),
                ('bank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.bank', verbose_name='الحساب البنكي')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='أنشأه')),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partners.farmer', verbose_name='الرعوي')),
            ],
            options={
                'verbose_name': 'سند صرف',
                'verbose_name_plural': 'سندات الصرف',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DailySettlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='التاريخ')),
                ('received_value', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='قيمة المستلم')),
                ('sold_value', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='قيمة المباع')),
                ('commission', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='العمولة')),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='الخصم')),
                ('expense', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='المصروف')),
                ('net_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='الصافي')),
                ('is_settled', models.BooleanField(default=False, verbose_name='تم التسوية')),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partners.farmer', verbose_name='الرعوي')),
                ('settlement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.farmersettlement', verbose_name='التسوية')),
            ],
            options={
                'verbose_name': 'تسوية يومية',
                'verbose_name_plural': 'التسويات اليومية',
                'ordering': ['-date'],
                'unique_together': {('farmer', 'date')},
            },
        ),
    ]
