# Generated by Django 6.0.7 on 2026-07-10 23:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('partners', '0001_initial'),
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='الاسم')),
                ('name_en', models.CharField(blank=True, max_length=200, verbose_name='الاسم بالإنجليزية')),
                ('address', models.TextField(blank=True, verbose_name='العنوان')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='الهاتف')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
            ],
            options={
                'verbose_name': 'فرع',
                'verbose_name_plural': 'الفروع',
            },
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='الكود')),
                ('name', models.CharField(max_length=100, verbose_name='الاسم')),
                ('name_en', models.CharField(blank=True, max_length=100, verbose_name='الاسم بالإنجليزية')),
                ('symbol', models.CharField(max_length=10, verbose_name='الرمز')),
                ('is_default', models.BooleanField(default=False, verbose_name='العملة الافتراضية')),
                ('exchange_rate', models.DecimalField(decimal_places=4, default=1.0, max_digits=12, verbose_name='سعر الصرف')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
            ],
            options={
                'verbose_name': 'عملة',
                'verbose_name_plural': 'العملات',
            },
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='الكود')),
                ('name', models.CharField(max_length=100, verbose_name='الاسم')),
                ('name_en', models.CharField(blank=True, max_length=100, verbose_name='الاسم بالإنجليزية')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
            ],
            options={
                'verbose_name': 'طريقة دفع',
                'verbose_name_plural': 'طرق الدفع',
            },
        ),
        migrations.CreateModel(
            name='AccountType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='الكود')),
                ('name', models.CharField(max_length=200, verbose_name='الاسم')),
                ('name_en', models.CharField(blank=True, max_length=200, verbose_name='الاسم بالإنجليزية')),
                ('account_type', models.CharField(choices=[('ASSETS', 'الأصول'), ('LIABILITIES', 'الخصوم'), ('EQUITY', 'حقوق الملكية'), ('REVENUE', 'الإيرادات'), ('EXPENSES', 'المصروفات')], max_length=20, verbose_name='نوع الحساب')),
                ('level', models.PositiveIntegerField(default=1, verbose_name='المستوى')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='core.accounttype', verbose_name='الحساب الأب')),
            ],
            options={
                'verbose_name': 'نوع حساب',
                'verbose_name_plural': 'أنواع الحسابات',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='CommissionRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='الاسم')),
                ('rule_type', models.CharField(choices=[('FIXED_PERCENT', 'نسبة ثابتة'), ('FARMER_SPECIFIC', 'نسبة حسب الرعوي'), ('PRODUCT_SPECIFIC', 'نسبة حسب الصنف'), ('SEASONAL', 'نسبة حسب الموسم'), ('FIXED_AMOUNT', 'مبلغ ثابت'), ('FORMULA', 'معادلة مخصصة')], max_length=20, verbose_name='نوع القاعدة')),
                ('value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='القيمة')),
                ('formula', models.TextField(blank=True, help_text='مثال: price * 0.05 + 10', verbose_name='المعادلة')),
                ('season_start', models.DateField(blank=True, null=True, verbose_name='بداية الموسم')),
                ('season_end', models.DateField(blank=True, null=True, verbose_name='نهاية الموسم')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('priority', models.PositiveIntegerField(default=0, verbose_name='الأولوية')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('farmer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='partners.farmer', verbose_name='الرعوي')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='الصنف')),
            ],
            options={
                'verbose_name': 'قاعدة عمولة',
                'verbose_name_plural': 'قواعد العمولة',
            },
        ),
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم البنك')),
                ('account_number', models.CharField(max_length=50, unique=True, verbose_name='رقم الحساب')),
                ('iban', models.CharField(blank=True, max_length=50, verbose_name='الآيبان')),
                ('branch_name', models.CharField(blank=True, max_length=200, verbose_name='اسم الفرع')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='الرصيد')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.currency', verbose_name='العملة')),
            ],
            options={
                'verbose_name': 'حساب بنكي',
                'verbose_name_plural': 'الحسابات البنكية',
            },
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='الكود')),
                ('name', models.CharField(max_length=200, verbose_name='الاسم')),
                ('name_en', models.CharField(blank=True, max_length=200, verbose_name='الاسم بالإنجليزية')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='الرصيد')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_accounts', to='core.account', verbose_name='الحساب الأب')),
                ('account_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.accounttype', verbose_name='نوع الحساب')),
                ('currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.currency', verbose_name='العملة')),
            ],
            options={
                'verbose_name': 'حساب',
                'verbose_name_plural': 'الحسابات',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='الاسم')),
                ('name_en', models.CharField(blank=True, max_length=200, verbose_name='الاسم بالإنجليزية')),
                ('is_default', models.BooleanField(default=False, verbose_name='المخزن الافتراضي')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.branch', verbose_name='الفرع')),
            ],
            options={
                'verbose_name': 'مخزن',
                'verbose_name_plural': 'المخازن',
            },
        ),
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='الوساطة الزراعية', max_length=300, verbose_name='اسم المؤسسة')),
                ('company_name_en', models.CharField(default='Agri Bridge', max_length=300, verbose_name='اسم المؤسسة بالإنجليزية')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='settings/', verbose_name='الشعار')),
                ('address', models.TextField(blank=True, verbose_name='العنوان')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='الهاتف')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='البريد الإلكتروني')),
                ('website', models.URLField(blank=True, verbose_name='الموقع الإلكتروني')),
                ('commission_percentage', models.DecimalField(decimal_places=2, default=5.0, max_digits=5, verbose_name='نسبة العمولة الافتراضية')),
                ('tax_enabled', models.BooleanField(default=False, verbose_name='تفعيل الضرائب')),
                ('tax_percentage', models.DecimalField(decimal_places=2, default=15.0, max_digits=5, verbose_name='نسبة الضريبة')),
                ('print_thermal_58', models.BooleanField(default=True, verbose_name='طباعة حرارية 58mm')),
                ('print_thermal_80', models.BooleanField(default=False, verbose_name='طباعة حرارية 80mm')),
                ('print_a4', models.BooleanField(default=False, verbose_name='طباعة A4')),
                ('invoice_copies', models.PositiveIntegerField(default=2, verbose_name='عدد نسخ الفاتورة')),
                ('default_language', models.CharField(choices=[('ar', 'العربية'), ('en', 'English')], default='ar', max_length=5, verbose_name='اللغة الافتراضية')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.currency', verbose_name='العملة الافتراضية')),
                ('default_branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.branch', verbose_name='الفرع الافتراضي')),
                ('default_warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.warehouse', verbose_name='المخزن الافتراضي')),
            ],
            options={
                'verbose_name': 'إعدادات النظام',
                'verbose_name_plural': 'إعدادات النظام',
            },
        ),
        migrations.CreateModel(
            name='PeriodLock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_type', models.CharField(choices=[('DAILY', 'يومي'), ('MONTHLY', 'شهري'), ('YEARLY', 'سنوي')], max_length=10, verbose_name='نوع الفترة')),
                ('start_date', models.DateField(verbose_name='تاريخ البداية')),
                ('end_date', models.DateField(verbose_name='تاريخ النهاية')),
                ('is_locked', models.BooleanField(default=False, verbose_name='مقفل')),
                ('locked_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإقفال')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('locked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'إقفال فترة',
                'verbose_name_plural': 'إقفال الفترات',
                'unique_together': {('period_type', 'start_date', 'end_date')},
            },
        ),
    ]
