# Generated by Django 6.0.7 on 2026-07-10 23:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='رقم العميل')),
                ('name', models.CharField(max_length=200, verbose_name='الاسم')),
                ('name_en', models.CharField(blank=True, max_length=200, verbose_name='الاسم بالإنجليزية')),
                ('phone', models.CharField(max_length=50, verbose_name='رقم الهاتف')),
                ('address', models.TextField(blank=True, verbose_name='العنوان')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='المدينة')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('credit_limit', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='الحد الائتماني')),
                ('status', models.CharField(choices=[('ACTIVE', 'نشط'), ('INACTIVE', 'غير نشط'), ('SUSPENDED', 'موقوف')], default='ACTIVE', max_length=10, verbose_name='الحالة')),
                ('current_balance', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='الرصيد الحالي')),
                ('total_purchases', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='إجمالي المشتريات')),
                ('total_paid', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='إجمالي المسدد')),
                ('total_remaining', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='إجمالي المتبقي')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'مقوت',
                'verbose_name_plural': 'المقاوته',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Farmer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='رقم الرعوي')),
                ('name', models.CharField(max_length=200, verbose_name='الاسم')),
                ('name_en', models.CharField(blank=True, max_length=200, verbose_name='الاسم بالإنجليزية')),
                ('phone', models.CharField(max_length=50, verbose_name='رقم الهاتف')),
                ('id_number', models.CharField(blank=True, max_length=50, verbose_name='رقم الهوية')),
                ('address', models.TextField(blank=True, verbose_name='العنوان')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='المدينة')),
                ('region', models.CharField(blank=True, max_length=100, verbose_name='المنطقة')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('status', models.CharField(choices=[('ACTIVE', 'نشط'), ('INACTIVE', 'غير نشط'), ('SUSPENDED', 'معلق')], default='ACTIVE', max_length=10, verbose_name='الحالة')),
                ('current_balance', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='الرصيد الحالي')),
                ('total_receivables', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='إجمالي المستحقات')),
                ('total_paid', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='إجمالي المدفوع')),
                ('total_discounts', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='إجمالي الخصومات')),
                ('total_commissions', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='إجمالي العمولات')),
                ('total_expenses', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='إجمالي المصروفات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'رعوي',
                'verbose_name_plural': 'الرعويون',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='الاسم')),
                ('discount_type', models.CharField(choices=[('FIXED_AMOUNT', 'مبلغ ثابت'), ('PERCENTAGE', 'نسبة'), ('TEMPORARY', 'مؤقت'), ('PERMANENT', 'دائم')], max_length=20, verbose_name='نوع الخصم')),
                ('target_type', models.CharField(choices=[('FARMER', 'رعوي'), ('BUYER', 'مقوت'), ('INVOICE', 'فاتورة'), ('ALL', 'جميع الفواتير')], max_length=20, verbose_name='نوع المستهدف')),
                ('value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='القيمة')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='تاريخ البداية')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='تاريخ النهاية')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('target_buyer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='partners.buyer', verbose_name='الرعوي المستهدف')),
                ('target_farmer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='partners.farmer', verbose_name='الرعوي المستهدف')),
            ],
            options={
                'verbose_name': 'خصم',
                'verbose_name_plural': 'الخصومات',
            },
        ),
    ]
