# Generated by Django 6.0.7 on 2026-07-10 23:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cashbox', '0001_initial'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='الاسم')),
                ('name_en', models.CharField(blank=True, max_length=200, verbose_name='الاسم بالإنجليزية')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.account', verbose_name='الحساب المحاسبي')),
            ],
            options={
                'verbose_name': 'تصنيف مصروفات',
                'verbose_name_plural': 'تصنيفات المصروفات',
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voucher_number', models.CharField(max_length=50, unique=True, verbose_name='رقم السند')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='المبلغ')),
                ('payment_method', models.CharField(choices=[('CASH', 'نقدي'), ('BANK_TRANSFER', 'تحويل بنكي'), ('CHECK', 'شيك'), ('OTHER', 'أخرى')], default='CASH', max_length=20, verbose_name='طريقة الدفع')),
                ('beneficiary', models.CharField(blank=True, max_length=300, verbose_name='المستفيد')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='expenses/attachments/', verbose_name='المرفق')),
                ('date', models.DateField(verbose_name='التاريخ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='محذوف')),
                ('bank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.bank', verbose_name='الحساب البنكي')),
                ('cashbox', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cashbox.cashbox', verbose_name='الصندوق')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='أنشأه')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expenses.expensecategory', verbose_name='التصنيف')),
            ],
            options={
                'verbose_name': 'مصروف',
                'verbose_name_plural': 'المصروفات',
                'ordering': ['-date'],
            },
        ),
    ]
