# Generated by Django 5.2.16 on 2026-07-11 13:59

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                error_messages={"unique": "اسم المستخدم موجود مسبقاً."},
                help_text="مطلوب. 150 حرف أو أقل. حروف وأرقام و @/./+/-/_ فقط.",
                max_length=150,
                unique=True,
                validators=[django.contrib.auth.validators.UnicodeUsernameValidator()],
                verbose_name="اسم المستخدم",
            ),
        ),
    ]
