# Generated by Django 5.2.16 on 2026-07-11 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_user_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="webauthn_credential_id",
            field=models.TextField(blank=True, null=True, verbose_name="معرف البصمة"),
        ),
        migrations.AddField(
            model_name="user",
            name="webauthn_enabled",
            field=models.BooleanField(default=False, verbose_name="تفعيل البصمة"),
        ),
        migrations.AddField(
            model_name="user",
            name="webauthn_public_key",
            field=models.TextField(blank=True, null=True, verbose_name="مفتاح البصمة"),
        ),
    ]
