# Generated by Django 6.0.7 on 2026-07-10 23:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adjustment_qty', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='كمية التسوية')),
                ('reason', models.TextField(verbose_name='السبب')),
                ('is_approved', models.BooleanField(default=False, verbose_name='معتمد')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='المعتمد')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='الصنف')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.warehouse', verbose_name='المخزن')),
            ],
            options={
                'verbose_name': 'تسوية مخزون',
                'verbose_name_plural': 'تسويات المخزون',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InventoryMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('RECEIVED', 'استلام'), ('SOLD', 'بيع'), ('RETURN_IN', 'مرتجع إلى الرعوي'), ('RETURN_OUT', 'مرتجع من المقوت'), ('DAMAGED', 'تالف'), ('WASTED', 'هالك'), ('LOST', 'مفقود'), ('STOLEN', 'مسروق'), ('TRANSFER_IN', 'تحويل وارد'), ('TRANSFER_OUT', 'تحويل صادر')], max_length=20, verbose_name='نوع الحركة')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='الكمية')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='السعر')),
                ('reference_type', models.CharField(blank=True, max_length=50, verbose_name='نوع المرجع')),
                ('reference_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='رقم المرجع')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('reason', models.TextField(blank=True, verbose_name='السبب')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_movements', to=settings.AUTH_USER_MODEL, verbose_name='أنشأه')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='الصنف')),
                ('responsible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='المسؤول')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.unit', verbose_name='الوحدة')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.warehouse', verbose_name='المخزن')),
            ],
            options={
                'verbose_name': 'حركة مخزون',
                'verbose_name_plural': 'حركات المخزون',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('received_qty', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='الكمية المستلمة')),
                ('sold_qty', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='الكمية المباعة')),
                ('remaining_qty', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='الكمية المتبقية')),
                ('returned_qty', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='الكمية المرتجعة')),
                ('damaged_qty', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='الكمية التالفة')),
                ('reserved_qty', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='الكمية المحجوزة')),
                ('avg_price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='المتوسط السعري')),
                ('last_buy_price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='آخر سعر شراء')),
                ('last_sell_price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='آخر سعر بيع')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='الصنف')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.warehouse', verbose_name='المخزن')),
            ],
            options={
                'verbose_name': 'مخزون صنف',
                'verbose_name_plural': 'المخزون',
                'unique_together': {('product', 'warehouse')},
            },
        ),
    ]
