# Generated by Django 6.0.7 on 2026-07-10 23:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATE', 'إنشاء'), ('UPDATE', 'تعديل'), ('DELETE', 'حذف'), ('APPROVE', 'اعتماد'), ('REJECT', 'رفض'), ('CANCEL', 'إلغاء'), ('LOGIN', 'تسجيل دخول'), ('LOGOUT', 'خروج'), ('PASSWORD_CHANGE', 'تغيير كلمة المرور'), ('PERMISSION_CHANGE', 'تغيير صلاحيات'), ('LOCK_PERIOD', 'إقفال فترة'), ('UNLOCK_PERIOD', 'فتح فترة')], max_length=20, verbose_name='العملية')),
                ('model_name', models.CharField(max_length=100, verbose_name='النموذج')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='رقم الكائن')),
                ('object_repr', models.CharField(blank=True, max_length=300, verbose_name='وصف الكائن')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='عنوان IP')),
                ('user_agent', models.CharField(blank=True, max_length=500, verbose_name='الجهاز')),
                ('old_data', models.JSONField(blank=True, default=dict, verbose_name='البيانات قبل')),
                ('new_data', models.JSONField(blank=True, default=dict, verbose_name='البيانات بعد')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='التاريخ والوقت')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'سجل عملية',
                'verbose_name_plural': 'سجلات العمليات',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', 'timestamp'], name='audit_audit_user_id_e8be02_idx'), models.Index(fields=['model_name', 'object_id'], name='audit_audit_model_n_20c0d3_idx'), models.Index(fields=['action', 'timestamp'], name='audit_audit_action_2a1328_idx')],
            },
        ),
    ]
