# Generated by Django 6.0.7 on 2026-07-10 23:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CashBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='الاسم')),
                ('name_en', models.CharField(blank=True, max_length=200, verbose_name='الاسم بالإنجليزية')),
                ('opening_balance', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='الرصيد الافتتاحي')),
                ('current_balance', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='الرصيد الحالي')),
                ('status', models.CharField(choices=[('OPEN', 'مفتوح'), ('CLOSED', 'مغلق'), ('SUSPENDED', 'معلق')], default='OPEN', max_length=10, verbose_name='الحالة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.branch', verbose_name='الفرع')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='أنشأه')),
            ],
            options={
                'verbose_name': 'صندوق',
                'verbose_name_plural': 'الصناديق',
            },
        ),
        migrations.CreateModel(
            name='CashTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('INCOME', 'وارد'), ('EXPENSE', 'صادر'), ('OPENING', 'رصيد افتتاحي'), ('CLOSING', 'رصيد إقفالي'), ('TRANSFER_IN', 'تحويل وارد'), ('TRANSFER_OUT', 'تحويل صادر')], max_length=15, verbose_name='نوع الحركة')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='المبلغ')),
                ('description', models.TextField(verbose_name='الوصف')),
                ('reference_type', models.CharField(blank=True, max_length=50, verbose_name='نوع المرجع')),
                ('reference_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='رقم المرجع')),
                ('balance_before', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='الرصيد قبل')),
                ('balance_after', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='الرصيد بعد')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='محذوف')),
                ('cashbox', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cashbox.cashbox', verbose_name='الصندوق')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='أنشأه')),
            ],
            options={
                'verbose_name': 'حركة صندوق',
                'verbose_name_plural': 'حركات الصناديق',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DailyCashClosing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='التاريخ')),
                ('opening_balance', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='الرصيد الافتتاحي')),
                ('total_income', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='إجمالي الوارد')),
                ('total_expense', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='إجمالي الصادر')),
                ('closing_balance', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='الرصيد الإقفالي')),
                ('expected_balance', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='الرصيد المتوقع')),
                ('difference', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='الفرق')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('cashbox', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cashbox.cashbox', verbose_name='الصندوق')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='أنشأه')),
            ],
            options={
                'verbose_name': 'إقفال يومي',
                'verbose_name_plural': 'الإقفالات اليومية',
                'ordering': ['-date'],
                'unique_together': {('cashbox', 'date')},
            },
        ),
    ]
