# Generated by Django 6.0.7 on 2026-07-10 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_type', models.CharField(choices=[('DAILY', 'يومي'), ('MONTHLY', 'شهري'), ('YEARLY', 'سنوي')], max_length=10, verbose_name='نوع الفترة')),
                ('start_date', models.DateField(verbose_name='تاريخ البداية')),
                ('end_date', models.DateField(verbose_name='تاريخ النهاية')),
                ('is_closed', models.BooleanField(default=False, verbose_name='مغلق')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الإغلاق')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
            ],
            options={
                'verbose_name': 'فترة مالية',
                'verbose_name_plural': 'الفترات المالية',
                'ordering': ['-end_date'],
            },
        ),
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_number', models.CharField(max_length=50, unique=True, verbose_name='رقم القيد')),
                ('date', models.DateField(verbose_name='التاريخ')),
                ('time', models.TimeField(auto_now_add=True, verbose_name='الوقت')),
                ('description', models.TextField(verbose_name='الوصف')),
                ('total_debit', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='إجمالي المدين')),
                ('total_credit', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='إجمالي الدائن')),
                ('status', models.CharField(choices=[('DRAFT', 'مسودة'), ('PENDING', 'بانتظار الاعتماد'), ('APPROVED', 'معتمد'), ('POSTED', 'مرحل'), ('CANCELLED', 'ملغي')], default='DRAFT', max_length=10, verbose_name='الحالة')),
                ('reference_type', models.CharField(blank=True, max_length=50, verbose_name='نوع المرجع')),
                ('reference_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='رقم المرجع')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='accounting/attachments/', verbose_name='المرفق')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الاعتماد')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='محذوف')),
            ],
            options={
                'verbose_name': 'قيد يومي',
                'verbose_name_plural': 'القيود اليومية',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JournalEntryLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=300, verbose_name='الوصف')),
                ('debit', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='المدين')),
                ('credit', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='الدائن')),
                ('partner_type', models.CharField(blank=True, choices=[('FARMER', 'رعوي'), ('BUYER', 'مقوت')], max_length=10, null=True, verbose_name='نوع الشريك')),
                ('partner_obj_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='رقم الشريك')),
            ],
            options={
                'verbose_name': 'سطر قيد',
                'verbose_name_plural': 'سطور القيود',
            },
        ),
        migrations.CreateModel(
            name='LedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='التاريخ')),
                ('description', models.CharField(max_length=300, verbose_name='الوصف')),
                ('debit', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='المدين')),
                ('credit', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='الدائن')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='الرصيد')),
                ('balance_type', models.CharField(choices=[('DEBIT', 'مدين'), ('CREDIT', 'دائن')], default='DEBIT', max_length=10, verbose_name='نوع الرصيد')),
            ],
            options={
                'verbose_name': 'سجل أستاذ',
                'verbose_name_plural': 'سجلات الأستاذ',
                'ordering': ['date', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TrialBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='التاريخ')),
                ('opening_balance', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='الرصيد الافتتاحي')),
                ('total_debit', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='إجمالي المدين')),
                ('total_credit', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='إجمالي الدائن')),
                ('closing_balance', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='الرصيد الختامي')),
                ('balance_type', models.CharField(choices=[('DEBIT', 'مدين'), ('CREDIT', 'دائن')], default='DEBIT', max_length=10, verbose_name='نوع الرصيد')),
            ],
            options={
                'verbose_name': 'ميزان مراجعة',
                'verbose_name_plural': 'ميزان المراجعة',
            },
        ),
    ]
